export const EquipmentTypes = {
  'AGITADORES-CENTRIFUGAS': 'AGITADORES Y CENTRIFUGAS',
  BAÑOS: 'BAÑOS',
  'EQUIPO GENERAL': 'EQUIPO GENERAL',
  'EQUIPO-PCR': 'EQUIPO PARA PCR',
  ESTERILIZACION: 'ESTERILIZACION',
  'ESTUFAS,INCUBADORAS Y MUFLAS': 'ESTUFAS,INCUBADORAS Y MUFLAS',
  'MEDIDORES-SONDAS-PHMTS': 'MEDIDORES,SONDAS Y PHmetros',
  OPTICA: 'OPTICA',
  'QUIMICA-ANALITICA': 'QUÍMICA ANALÍTICA',
  'SALIDA-CAMPO-ANALISIS-AGUA': 'SALIDA DE CAMPO Y ANÁLISIS DE AGUA',
  'SISTEMAS-MEDICION': 'SISTEMAS DE MEDICION',
} as const;

export type EquipmentTypeValue =
  (typeof EquipmentTypes)[keyof typeof EquipmentTypes];

export type EquipmentType = keyof typeof EquipmentTypes;
