version: '3.8'

services:
  mongo1:
    image: 'mongo:8'
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./.mongo/data:/data/db
      - ./.mongo/logs:/var/log/mongodb
      - ./mongo/setup-scripts:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      KEYFILE_PATH: /data/configdb/mongo-keyfile
    command: >
      mongod --replSet rs0 --dbpath /data/db --auth --keyFile /data/configdb/mongo-keyfile --bind_ip localhost,mongo1
    healthcheck:
      test: "mongo --eval 'rs.initiate()' || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      mongo-net:
        aliases:
          - mongo1

  setup:
    image: mongo:8
    depends_on:
      - mongo1
    volumes:
      - ./mongo/setup-replicaset.sh:/scripts/setup-replicaset.sh
    restart: 'no'
    entrypoint: ['bash', '/scripts/setup-replicaset.sh']
    environment:
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD: example
      MONGO_ROOT_DATABASE: admin
      MONGO_HOST: mongo1
      MONGO_PORT: 27017
    networks:
      mongo-net:
        aliases:
          - mongo_setup

networks:
  mongo-net:
    driver: bridge
