### Get all available/unused tokens
GET http://localhost:3000/auth/register/token?isAvailable=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjZlYzA1ZGUwNDY2ZGE4ODVkZDVhYSIsInJvbGUiOltdLCJuYW1lIjoicmljayIsImxhc3ROYW1lIjoic2FuY2hleiIsImVtYWlsIjoicnNhbmNoZXpAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzA2MDQwNjMsImV4cCI6MTczMDYwNzY2M30.MdRLoQjNuvMkKz0BaOKbPyUiHUB0jSM-VGObGgJxW7k

### Create a new register token
POST http://localhost:3000/auth/register/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjZlYzA1ZGUwNDY2ZGE4ODVkZDVhYSIsInJvbGUiOltdLCJuYW1lIjoicmljayIsImxhc3ROYW1lIjoic2FuY2hleiIsImVtYWlsIjoicnNhbmNoZXpAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzA2MDQwNjMsImV4cCI6MTczMDYwNzY2M30.MdRLoQjNuvMkKz0BaOKbPyUiHUB0jSM-VGObGgJxW7k

### Delete a register token
DELETE http://localhost:3000/auth/register/token/<OTP>
Content-Tzype: application/json

### Register User
POST http://localhost:3000/auth/register?token=6726ebfdde0466da885dd5a6
Content-Type: application/json

{
    "name": "rick",
    "lastName": "sanchez",
    "password": "piclkeRick1",
    "email": "rsanchez@example.com",
    "dni": 1234
}

### Login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "rsanchez@example.com",
    "password": "piclkeRick1"
}