### Get Single
GET  http://localhost:3000/material/66df4e93fc31884f2ddb5255
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDc4NWNlNzQ2OGZmZTcyMWEyMzkwZSIsInJvbGUiOlsiTUFTVEVSIE9GIFRIRSBVTklWRVJTRSIsIlVOSVZFUlNFIE9GIFRIRSBNQVNURVIiXSwibmFtZSI6InJpY2siLCJsYXN0TmFtZSI6InNhbmNoZXoiLCJlbWFpbCI6InJzYW5jaGV6QGV4YW1wbGUuY29tIiwiaWF0IjoxNzI1OTE1Nzk4LCJleHAiOjE3MjU5MTkzOTh9.hcQfSfIxhGPoTrLrw6eD0f_hcGEOuDgbc8GXp8PsfXY

### Get All
GET  http://localhost:3000/material
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDc4NWNlNzQ2OGZmZTcyMWEyMzkwZSIsInJvbGUiOlsiTUFTVEVSIE9GIFRIRSBVTklWRVJTRSIsIlVOSVZFUlNFIE9GIFRIRSBNQVNURVIiXSwibmFtZSI6InJpY2siLCJsYXN0TmFtZSI6InNhbmNoZXoiLCJlbWFpbCI6InJzYW5jaGV6QGV4YW1wbGUuY29tIiwiaWF0IjoxNzI1OTE1Nzk4LCJleHAiOjE3MjU5MTkzOTh9.hcQfSfIxhGPoTrLrw6eD0f_hcGEOuDgbc8GXp8PsfXY


### Add Material
POST http://localhost:3000/material
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDc4NWNlNzQ2OGZmZTcyMWEyMzkwZSIsInJvbGUiOlsiTUFTVEVSIE9GIFRIRSBVTklWRVJTRSIsIlVOSVZFUlNFIE9GIFRIRSBNQVNURVIiXSwibmFtZSI6InJpY2siLCJsYXN0TmFtZSI6InNhbmNoZXoiLCJlbWFpbCI6InJzYW5jaGV6QGV4YW1wbGUuY29tIiwiaWF0IjoxNzI1OTE1Nzk4LCJleHAiOjE3MjU5MTkzOTh9.hcQfSfIxhGPoTrLrw6eD0f_hcGEOuDgbc8GXp8PsfXY
Content-Type: application/json

{

    "description": "material falso",
    "unitMeasure": "u",
    "type": "falso",
    "stock": 123,
    "isAvailable": true,
    "inUse": []

}

### Update Material
PUT http://localhost:3000/material/66df4e93fc31884f2ddb5255
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDc4NWNlNzQ2OGZmZTcyMWEyMzkwZSIsInJvbGUiOlsiTUFTVEVSIE9GIFRIRSBVTklWRVJTRSIsIlVOSVZFUlNFIE9GIFRIRSBNQVNURVIiXSwibmFtZSI6InJpY2siLCJsYXN0TmFtZSI6InNhbmNoZXoiLCJlbWFpbCI6InJzYW5jaGV6QGV4YW1wbGUuY29tIiwiaWF0IjoxNzI1OTE1Nzk4LCJleHAiOjE3MjU5MTkzOTh9.hcQfSfIxhGPoTrLrw6eD0f_hcGEOuDgbc8GXp8PsfXY
Content-Type: application/json

{
    "stock": 124
}

### Delete Material
DELETE http://localhost:3000/material/66df4e93fc31884f2ddb5255
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDc4NWNlNzQ2OGZmZTcyMWEyMzkwZSIsInJvbGUiOlsiTUFTVEVSIE9GIFRIRSBVTklWRVJTRSIsIlVOSVZFUlNFIE9GIFRIRSBNQVNURVIiXSwibmFtZSI6InJpY2siLCJsYXN0TmFtZSI6InNhbmNoZXoiLCJlbWFpbCI6InJzYW5jaGV6QGV4YW1wbGUuY29tIiwiaWF0IjoxNzI1OTE1Nzk4LCJleHAiOjE3MjU5MTkzOTh9.hcQfSfIxhGPoTrLrw6eD0f_hcGEOuDgbc8GXp8PsfXY

### Get Types
GET  http://localhost:3000/material/constants/types
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDc4NWNlNzQ2OGZmZTcyMWEyMzkwZSIsInJvbGUiOlsiTUFTVEVSIE9GIFRIRSBVTklWRVJTRSIsIlVOSVZFUlNFIE9GIFRIRSBNQVNURVIiXSwibmFtZSI6InJpY2siLCJsYXN0TmFtZSI6InNhbmNoZXoiLCJlbWFpbCI6InJzYW5jaGV6QGV4YW1wbGUuY29tIiwiaWF0IjoxNzI1OTE1Nzk4LCJleHAiOjE3MjU5MTkzOTh9.hcQfSfIxhGPoTrLrw6eD0f_hcGEOuDgbc8GXp8PsfXY
