### Get Statuses
GET  http://localhost:3000/request/constants/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Mjk3MTllMWY2YjhhODE2YWZlZTZiMSIsInJvbGVzIjpbImFkbWluIiwibGFiIl0sIm5hbWUiOiJBZG1pbiIsImxhc3ROYW1lIjoiVXNlciIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3MzA4NTYwNjUsImV4cCI6MTczMDk0MjQ2NX0.MDHYTi-afiVcUJ7TPVUPMsXkk8wYLvhdq306adZxsx0
